# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20161018_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
