# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_subject_section_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='university',
            new_name='department',
        ),
    ]
