# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20161023_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_section_day',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_section', to='tables.Section'),
        ),
        migrations.AlterField(
            model_name='subject_section_day',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject', to='tables.Subject'),
        ),
    ]
