# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20161026_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_section_day',
            name='period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
