# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_subject_section_day_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject_section_day',
            new_name='table',
        ),
    ]
