# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20161028_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('active', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='day',
            field=models.IntegerField(),
        ),
    ]
