# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20161031_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='off_days',
            field=models.CharField(default='sat', max_length=5),
            preserve_default=False,
        ),
    ]
